apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo
spec:
  interval: 1m
  url: https://github.com/adeel-ifti/gcp-automation-modules.git
  ref:
    branch: main
  secretRef:
    name: git-auth
