
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-app
spec:
  interval: 20s
  releaseName: "nginx-app-release"
  chart:
    spec:
      chart: charts/nginx
      sourceRef:
        kind: GitRepository
        name: flux-demo
      interval: 20s